# Elastic Search Variables
elasticsearch_host: localhost
systemd_src: elastic-timeout.conf

# Kibana Variables
kibana_host: localhost

# Logstash Variables
logstash_conf: logstash.conf

# Nagios Variables
nagios_user: nagiosadmin
nagios_password: password

# LAMP Variables
domain: millerpunla
owner: millerpunla
group: millerpunla
index_html: index.html
ubuntu_src: qjmepunla-tip-ubuntu.conf
centos_src: qjmepunla-tip-centos.conf
